import 'package:dio/dio.dart';
import 'package:fake_cloud_firestore/fake_cloud_firestore.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:recipe_ai/ddd/entity.dart';
import 'package:recipe_ai/receipe/infrastructure/receipe_repository_v2.dart';

void main() {
  late FakeFirebaseFirestore firestore;
  late UserReceipeRepositoryV2 sut;

  const uid = EntityId('uid');

  setUp(() {
    firestore = FakeFirebaseFirestore();
    sut = UserReceipeRepositoryV2(firestore, Dio());
  });

  Future<void> addRecipe(String userId, Map<String, dynamic> data) => firestore
      .collection(UserReceipeRepositoryV2.userReceipeV2Collection)
      .doc(userId)
      .collection(UserReceipeRepositoryV2.receipesCollection)
      .add(data);

  test('counts the recipes generated by the user', () async {
    await addRecipe('uid', {'isAddedToFavorites': false});
    await addRecipe('uid', {'isAddedToFavorites': true});
    await addRecipe('other', {'isAddedToFavorites': false});

    expect(await sut.countGeneratedRecipes(uid), 2);
  });

  test('ignores the former home suggestions', () async {
    await addRecipe('uid', {'isForHome': false});
    await addRecipe('uid', {'isForHome': true});
    await addRecipe('uid', {});

    expect(await sut.countGeneratedRecipes(uid), 2);
  });

  test('is zero without any recipe', () async {
    expect(await sut.countGeneratedRecipes(uid), 0);
  });
}
