import 'dart:math' as math;

import 'package:flutter/material.dart';
import 'package:recipe_ai/di/container.dart';
import 'package:recipe_ai/user_account/presentation/translation_controller.dart';
import 'package:recipe_ai/utils/colors.dart';
import 'package:recipe_ai/utils/pot_icon.dart';

const _robotoFontFamily = 'Roboto';
const _robotoSlabFontFamily = 'RobotoSlab';

enum _StepState { pending, active, done }

class _Scene {
  const _Scene({
    required this.durationMs,
    required this.from,
    required this.to,
  });

  final int durationMs;
  final double from;
  final double to;
}

/// The three announced steps. The bar stops at [_holdProgress] and waits there
/// for as long as the generation takes: the last percents belong to the answer.
const _scenes = [
  _Scene(durationMs: 2000, from: 0.0, to: 0.30),
  _Scene(durationMs: 2000, from: 0.30, to: 0.62),
  _Scene(durationMs: 2000, from: 0.62, to: _holdProgress),
];

const _holdProgress = 0.9;
const _readyDurationMs = 1100;

/// Animated loader shown while a recipe is being generated by the AI.
///
/// Plays the scenes of the ecran-07-animation mockup — reading ingredients,
/// selecting the recipe, calculating quantities — then holds on the last one
/// for as long as the caller keeps [isReady] false. The ring only closes into
/// its checkmark and the title only becomes "your recipe is ready" once the
/// caller flips [isReady], i.e. once the API really answered with a recipe;
/// [onReadyAnimationEnd] then fires so the caller can show it.
class RecipeGenerationLoader extends StatefulWidget {
  const RecipeGenerationLoader({
    super.key,
    this.isReady = false,
    this.onReadyAnimationEnd,
  });

  /// True once the generation succeeded and the result is worth showing.
  final bool isReady;

  /// Called at the end of the "recipe ready" animation, once.
  final VoidCallback? onReadyAnimationEnd;

  @override
  State<RecipeGenerationLoader> createState() => _RecipeGenerationLoaderState();
}

class _RecipeGenerationLoaderState extends State<RecipeGenerationLoader>
    with TickerProviderStateMixin {
  static final _workMs = _scenes.fold<int>(0, (sum, s) => sum + s.durationMs);
  static final _sceneStartsMs = () {
    var acc = 0;
    return _scenes.map((s) {
      final start = acc;
      acc += s.durationMs;
      return start;
    }).toList();
  }();

  late final AnimationController _workController;
  late final AnimationController _readyController;
  late final AnimationController _ringController;

  /// Where the bar stood when the answer arrived, so it finishes from there
  /// instead of jumping backwards on a fast generation.
  double _progressWhenReady = _holdProgress;

  @override
  void initState() {
    super.initState();
    _workController = AnimationController(
      vsync: this,
      duration: Duration(milliseconds: _workMs),
    )..forward();
    _readyController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: _readyDurationMs),
    );
    _ringController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1100),
    )..repeat();

    if (widget.isReady) _playReady();
  }

  @override
  void didUpdateWidget(RecipeGenerationLoader oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.isReady && !oldWidget.isReady) _playReady();
  }

  void _playReady() {
    _progressWhenReady = _workingProgress();
    _readyController.forward().whenComplete(() {
      if (mounted) widget.onReadyAnimationEnd?.call();
    });
  }

  @override
  void dispose() {
    _workController.dispose();
    _readyController.dispose();
    _ringController.dispose();
    super.dispose();
  }

  static double _smooth(double t) {
    final c = t.clamp(0.0, 1.0);
    return c * c * (3 - 2 * c);
  }

  /// Index of the step being announced, and how far it has run.
  (int, double) _currentScene() {
    final elapsedMs = _workController.value * _workMs;
    for (var i = 0; i < _scenes.length; i++) {
      if (elapsedMs < _sceneStartsMs[i] + _scenes[i].durationMs) {
        final progress =
            (elapsedMs - _sceneStartsMs[i]) / _scenes[i].durationMs;
        return (i, progress.clamp(0.0, 1.0));
      }
    }
    return (_scenes.length - 1, 1.0);
  }

  double _workingProgress() {
    final (index, progress) = _currentScene();
    final scene = _scenes[index];
    return scene.from + (scene.to - scene.from) * _smooth(progress);
  }

  @override
  Widget build(BuildContext context) {
    final appTexts = di<TranslationController>().currentLanguage;
    final steps = [
      appTexts.recipeGenerationStepReadingIngredients,
      appTexts.recipeGenerationStepSelectingRecipe,
      appTexts.recipeGenerationStepCalculatingQuantities,
    ];
    final subtitles = [
      appTexts.recipeGenerationSubReadingIngredients,
      appTexts.recipeGenerationSubSelectingRecipe,
      appTexts.recipeGenerationSubCalculatingQuantities,
    ];

    return AnimatedBuilder(
      animation: Listenable.merge([
        _workController,
        _readyController,
        _ringController,
      ]),
      builder: (context, _) {
        final isReady = widget.isReady;
        final settle = _smooth(_readyController.value / 0.5);
        final (sceneIndex, sceneProgress) = _currentScene();

        final barValue = isReady
            ? _progressWhenReady +
                  (1 - _progressWhenReady) * _smooth(_readyController.value)
            : _workingProgress();
        final pulse = math.sin(_ringController.value * math.pi * 2) * 0.5 + 0.5;
        final subOpacity = isReady
            ? _smooth(_readyController.value / 0.3)
            : _smooth(sceneProgress / 0.14);

        return Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            _Ring(ringController: _ringController, settle: settle),
            const SizedBox(height: 24),
            Text(
              isReady
                  ? appTexts.recipeGenerationTitleReady
                  : appTexts.recipeGenerationTitle,
              style: const TextStyle(
                fontFamily: _robotoSlabFontFamily,
                fontWeight: FontWeight.w600,
                fontSize: 20,
                color: recipeLoaderInkColor,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 8),
            SizedBox(
              width: 250,
              child: Opacity(
                opacity: subOpacity.clamp(0.0, 1.0),
                child: Text(
                  isReady
                      ? appTexts.recipeGenerationSubReady
                      : subtitles[sceneIndex],
                  style: TextStyle(
                    fontFamily: _robotoFontFamily,
                    fontWeight: FontWeight.w400,
                    fontSize: 12.5,
                    height: 1.5,
                    color: recipeLoaderInkColor.withValues(alpha: 0.55),
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
            ),
            const SizedBox(height: 24),
            _ProgressBar(value: barValue),
            const SizedBox(height: 20),
            Column(
              children: List.generate(steps.length, (i) {
                final state = isReady || i < sceneIndex
                    ? _StepState.done
                    : i == sceneIndex
                    ? _StepState.active
                    : _StepState.pending;
                return Padding(
                  padding: EdgeInsets.only(top: i == 0 ? 0 : 12),
                  child: _StepRow(label: steps[i], state: state, pulse: pulse),
                );
              }),
            ),
          ],
        );
      },
    );
  }
}

class _Ring extends StatelessWidget {
  const _Ring({required this.ringController, required this.settle});

  final AnimationController ringController;
  final double settle;

  @override
  Widget build(BuildContext context) {
    final innerColor = Color.lerp(
      recipeLoaderMintColor,
      recipeLoaderGreenColor,
      settle,
    )!;

    return SizedBox(
      width: 96,
      height: 96,
      child: Stack(
        alignment: Alignment.center,
        children: [
          Container(
            width: 96,
            height: 96,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              border: Border.all(color: recipeLoaderMintColor, width: 3),
            ),
          ),
          Opacity(
            opacity: 1 - settle,
            child: RotationTransition(
              turns: ringController,
              child: CustomPaint(
                size: const Size(96, 96),
                painter: _ArcPainter(),
              ),
            ),
          ),
          Opacity(
            opacity: settle,
            child: Container(
              width: 96,
              height: 96,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                border: Border.all(color: recipeLoaderGreenColor, width: 3),
              ),
            ),
          ),
          Container(
            width: 56,
            height: 56,
            decoration: BoxDecoration(
              color: innerColor,
              shape: BoxShape.circle,
            ),
            child: Center(
              child: Stack(
                alignment: Alignment.center,
                children: [
                  Opacity(
                    opacity: 1 - settle,
                    child: const PotIcon(
                      size: 22,
                      color: recipeLoaderGreenColor,
                    ),
                  ),
                  Opacity(
                    opacity: settle,
                    child: Transform.scale(
                      scale: 0.7 + 0.3 * settle,
                      child: const Icon(
                        Icons.check,
                        size: 24,
                        color: Colors.white,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }
}

class _ArcPainter extends CustomPainter {
  @override
  void paint(Canvas canvas, Size size) {
    final rect = (Offset.zero & size).deflate(1.5);
    final paint = Paint()
      ..color = recipeLoaderGreenColor
      ..style = PaintingStyle.stroke
      ..strokeWidth = 3
      ..strokeCap = StrokeCap.round;
    canvas.drawArc(rect, -math.pi / 2, 100 * math.pi / 180, false, paint);
  }

  @override
  bool shouldRepaint(covariant CustomPainter oldDelegate) => false;
}

class _ProgressBar extends StatelessWidget {
  const _ProgressBar({required this.value});

  final double value;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 190,
      height: 6,
      clipBehavior: Clip.antiAlias,
      decoration: BoxDecoration(
        color: recipeLoaderInkColor.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(100),
      ),
      child: FractionallySizedBox(
        alignment: Alignment.centerLeft,
        widthFactor: value.clamp(0.0, 1.0),
        child: const DecoratedBox(
          decoration: BoxDecoration(color: recipeLoaderGreenColor),
        ),
      ),
    );
  }
}

class _StepRow extends StatelessWidget {
  const _StepRow({
    required this.label,
    required this.state,
    required this.pulse,
  });

  final String label;
  final _StepState state;
  final double pulse;

  @override
  Widget build(BuildContext context) {
    final done = state == _StepState.done;
    final active = state == _StepState.active;

    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Transform.scale(
          scale: active ? 1 + 0.1 * pulse : 1,
          child: Container(
            width: 20,
            height: 20,
            decoration: BoxDecoration(
              shape: BoxShape.circle,
              color: done || active
                  ? recipeLoaderGreenColor
                  : recipeLoaderInkColor.withValues(alpha: 0.12),
            ),
            child: Center(
              child: done
                  ? const Icon(Icons.check, size: 12, color: Colors.white)
                  : active
                  ? Container(
                      width: 7,
                      height: 7,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        color: Colors.white.withValues(
                          alpha: 0.55 + 0.45 * pulse,
                        ),
                      ),
                    )
                  : null,
            ),
          ),
        ),
        const SizedBox(width: 11),
        Text(
          label,
          style: TextStyle(
            fontFamily: _robotoFontFamily,
            fontWeight: active || done ? FontWeight.w600 : FontWeight.w400,
            fontSize: 12,
            color: active
                ? recipeLoaderInkColor
                : done
                ? recipeLoaderInkColor.withValues(alpha: 0.62)
                : recipeLoaderInkColor.withValues(alpha: 0.4),
          ),
        ),
      ],
    );
  }
}
