on: push

name: Continuous Integration

jobs:
  unit_test:
    name: Unit Testing
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - uses: dart-lang/setup-dart@v1
      - name: Install spec cli
        run: dart pub global activate spec_cli
      - name: Run tests
        run: spec --coverage
      - run: sudo apt-get install lcov
      - name: Gen html
        run: genhtml coverage/lcov.info -o coverage/html
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: coverage/html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: coverage/html
